version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      SUPABASE_URL: 'https://your-supabase-url.supabase.co'
      SUPABASE_KEY: 'your-supabase-key'
      MERCADO_PAGO_ACCESS_TOKEN: 'your-mercado-pago-access-token'
